
scan_timeout = 30
command_timeout = 500

# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[nodejs]
disabled = true

[gcloud]
disabled = true

[golang]
format = "[go@$version](bold fg:#99ff99) "

[directory]
truncation_length = 4
repo_root_style = "bold fg:#99ff99"

[git_branch]
style = "bold fg:#dc00f7"
format = "[$symbol$branch]($style) "

[hostname]
format = "[$hostname]($style)"
style = "bold fg:#ff295b"
ssh_only = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "â±  $duration "
style = "yellow"

# These symbols will only show when battery levels are 20% or less
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸ "

[[battery.display]]  # "bold red" style when capacity is between 0% and 20%
threshold = 20
discharging_symbol = "ğŸ’€"
style = "bold red"

[[battery.display]]  # "bold yello" style when capacity is between 0% and 50%
threshold = 50
style = "bold yellow"

[memory_usage]
symbol = "ï¡š "
disabled = false
threshold = 80

